-- ローカル開発専用。本番の service_checks は既存なので、このファイルは本番では実行しない
CREATE DATABASE IF NOT EXISTS status_dev CHARACTER SET utf8mb4;
USE status_dev;
DROP TABLE IF EXISTS service_checks;
CREATE TABLE service_checks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  service_id VARCHAR(64) NOT NULL,
  status ENUM('operational','degraded','outage') NOT NULL,
  response_time_ms INT NULL,
  status_code INT NULL,
  checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  checked_date DATE AS (DATE(checked_at)) STORED,
  KEY idx_svc_date (service_id, checked_date, status),
  KEY idx_svc_at (service_id, checked_at)
);
-- 直近120日 × 3分間隔 × 3サービス(ダミー)。一部に障害を混ぜる
INSERT INTO service_checks (service_id, status, response_time_ms, status_code, checked_at)
SELECT s.id,
  CASE WHEN n.i BETWEEN 3000 AND 3040 AND s.id='main' THEN 'outage'
       WHEN n.i BETWEEN 9000 AND 9012 AND s.id='main' THEN 'degraded'
       WHEN n.i BETWEEN 20000 AND 20100 AND s.id='timeline' THEN 'outage' ELSE 'operational' END,
  80 + (n.i*37 MOD 120), 200, NOW() - INTERVAL (n.i*3) MINUTE
FROM (SELECT 'main' id UNION SELECT 'timeline' UNION SELECT 'main-api') s
JOIN (SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 i FROM
 (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
 (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
 (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
 (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d,
 (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) e) n ON n.i < 57600;
